export const allCoins = [
	{
		name: "AAVE",
		pool: "3Pool",
		related: "DAI USDC USDT",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "USD",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
	},
	{
		name: "BTC",
		pool: "3Pool",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "BTC",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
		related: "DAI USDC USDT",
	},
	{
		name: "ONE",
		pool: "3Pool",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "ETH",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
		related: "DAI USDC USDT",
	},
	{
		name: "INCH",
		pool: "3Pool",
		related: "DAI USDC USDT",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "CRYPTO",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
	},
	{
		name: "ALGO",
		pool: "3Pool",
		related: "DAI USDC USDT",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "USD",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
	},
	{
		name: "AKRO",
		pool: "3Pool",
		related: "DAI USDC USDT",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "OTHERS",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
	},
	{
		name: "ONE",
		pool: "3Pool",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "ETH",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
		related: "DAI USDC USDT",
	},
	{
		name: "AKRO",
		pool: "3Pool",
		related: "DAI USDC USDT",
		address: "0x4dc******dec7",
		factory: "Factory",
		type: "OTHERS",
		base: "0.45%",
		volume: "$45.8m",
		tvl: "$545.8m",
	},
];
